services:
  # my_postgres:
  #   image: postgres:latest
  #   container_name: my_postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: my_database
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./src/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  #   networks:
  #     - my_network

  github-runner:
    image: ubuntu:22.04
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: github-runner
    privileged: true
    environment:
      REPO_URL: "https://github.com/peretzrickett/ariga"
      RUNNER_NAME: "my-runner"
      RUNNER_TOKEN: "AATMFF7FK3LYPOP2IPE5JPTG7IWBC"
      RUNNER_WORKDIR: "/tmp/github-runner"
      LABELS: "self-hosted,Linux,X64"
    networks:
      - my_network
    entrypoint: /usr/local/bin/start-runner.sh

networks:
  my_network:
    name: my_network
    driver: bridge
