services:
  my_postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - ./src/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - my_network

  github-runner:
    image: github-runner:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REPO_URL: ${REPO_URL}
        RUNNER_TOKEN: ${RUNNER_TOKEN}
        ATLAS_TOKEN: ${ATLAS_TOKEN}
        DATABASE_URL: postgres://postgres:postgres@my_postgres:5432/my_database?sslmode=disable
    container_name: github-runner
    privileged: true
    environment:
      REPO_URL: ${REPO_URL}
      RUNNER_NAME: "my-runner"
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_WORKDIR: "/tmp/github-runner"
      ATLAS_TOKEN: ${ATLAS_TOKEN}
      LABELS: "self-hosted,Linux,X64"
      DATABASE_URL: postgres://postgres:postgres@my_postgres:5432/my_database?sslmode=disable
    networks:
      - my_network
    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf

networks:
  my_network:
    name: my_network
    driver: bridge
