name: Atlas CI Schema Test
on:
  # Run whenever code is changed in the master branch,
  # change this to your root branch.
  push:
    branches:
      - main
  # Run on PRs where something changed under the `path/to/migration/dir/` directory.
#   pull_request:
#     paths:
#       - 'migrations/*'
jobs:
  test:
    services:
      # Spin up a postgres:17 container to be used as the dev-database for analysis.
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: dev
          POSTGRES_PASSWORD: pass
        ports:
          - 5433:5433
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
      - uses: ariga/atlas-action/schema/test@v1
        with:
          dev-url: postgres://postgres:pass@localhost:5433/dev